### ISSUE TITLE
Sound related problems

### ISSUE THREAD

**Issue by Tony-ATC** [Oddebit/ShootBadGuys#2]
J'ai relance l'app plusieurs fois et tester avec tous les Guns. Mais après chaque tire de "Gun"  la musique de fond s'arrête 1 sec pour lancer le son du gun.

- Faire en sorte que les sons se superpose

**Comment by Tony-ATC** [comment]
Second test. 
Le même problem persiste comme écrit en haut
Mais il n'y pas de problème de son avec le "reload" des guns et le background sound (la les son se superpose bien)

**Comment by Oddebit** [comment]
bizarre, chez moi ya pas...

**Comment by Tony-ATC** [comment]
Okey le problème de son vient de mes écouteurs je crois parce que quand je le lance via les haut-parleurs de mon pc le son est parfait 👍

**Comment by Tony-ATC** [comment]
Okey le problème de son vient de mes écouteurs je crois parce que quand je le lance via les haut-parleurs de mon pc le son est parfait 👍
